# Generated by Django 5.1.4 on 2025-01-02 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_number", models.CharField(max_length=20, unique=True)),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("001", "국민은행"),
                            ("002", "농협은행"),
                            ("003", "우리은행"),
                            ("004", "전북은행"),
                            ("005", "신한은행"),
                            ("006", "카카오뱅크"),
                            ("007", "토스뱅크"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "입출금"),
                            ("OVERDRAFT", "마이너스"),
                            ("SAVING", "적금"),
                            ("LOAN", "대출"),
                            ("PENSION", "연금"),
                            ("STOCK", "주식"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
